development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db

test:
  adapter: postgresql
  database: rcop_test
  encoding: unicode

production:
  adapter: postgresql
  encoding: unicode
  database: rcop_production
  pool: 3

